FROM maven:3.8.2-jdk-8-alpine
RUN apk add update \
          bash
COPY pom.xml /app/
COPY src app/src/
COPY ClipBoardHealthAssessment.sh /app/
WORKDIR  /app/
ENTRYPOINT ["/bin/sh"]
CMD ["ClipBoardHealthAssessment.sh"]